# Generated by Django 4.2.3 on 2023-07-12 06:15

from django.db import migrations, models
import playlist.models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0002_tag_album_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=playlist.models.image_upload_path),
        ),
    ]
